import { EUnit, ISpriteMetadata } from "./models/types";

export const terrainFilenames = [
  "plain",
  "mountain",
  "wood",
  "hriver",
  "vriver",
  "criver",
  "esriver",
  "swriver",
  "wnriver",
  "neriver",
  "eswriver",
  "swnriver",
  "wneriver",
  "nesriver",
  "hroad",
  "vroad",
  "croad",
  "esroad",
  "swroad",
  "wnroad",
  "neroad",
  "eswroad",
  "swnroad",
  "wneroad",
  "nesroad",
  "hbridge",
  "vbridge",
  "sea",
  "hshoal",
  "hshoaln",
  "vshoal",
  "vshoale",
  "reef",
  "neutralcity",
  "neutralbase",
  "neutralairport",
  "neutralport",
  "orangestarcity",
  "orangestarbase",
  "orangestarairport",
  "orangestarport",
  "orangestarhq",
  "bluemooncity",
  "bluemoonbase",
  "bluemoonairport",
  "bluemoonport",
  "bluemoonhq",
  "greenearthcity",
  "greenearthbase",
  "greenearthairport",
  "greenearthport",
  "greenearthhq",
  "yellowcometcity",
  "yellowcometbase",
  "yellowcometairport",
  "yellowcometport",
  "yellowcomethq",
  "redfirecity",
  "redfirebase",
  "redfireairport",
  "redfireport",
  "redfirehq",
  "greyskycity",
  "greyskybase",
  "greyskyairport",
  "greyskyport",
  "greyskyhq",
  "blackholecity",
  "blackholebase",
  "blackholeairport",
  "blackholeport",
  "blackholehq",
  "browndesertcity",
  "browndesertbase",
  "browndesertairport",
  "browndesertport",
  "browndeserthq",
  "vpipe",
  "hpipe",
  "nepipe",
  "espipe",
  "swpipe",
  "wnpipe",
  "npipeend",
  "epipeend",
  "spipeend",
  "wpipeend",
  "missilesilo",
  "missilesiloempty",
  "hpipeseam",
  "vpipeseam",
  "hpiperubble",
  "vpiperubble",
  "amberblazeairport",
  "amberblazebase",
  "amberblazecity",
  "amberblazehq",
  "amberblazeport",
  "jadesunairport",
  "jadesunbase",
  "jadesuncity",
  "jadesunhq",
  "jadesunport",
  "amberblazecomtower",
  "blackholecomtower",
  "bluemooncomtower",
  "browndesertcomtower",
  "greenearthcomtower",
  "jadesuncomtower",
  "neutralcomtower",
  "orangestarcomtower",
  "redfirecomtower",
  "yellowcometcomtower",
  "greyskycomtower",
  "amberblazelab",
  "blackholelab",
  "bluemoonlab",
  "browndesertlab",
  "greenearthlab",
  "greyskylab",
  "jadesunlab",
  "neutrallab",
  "orangestarlab",
  "redfirelab",
  "yellowcometlab",
  "cobalticeairport",
  "cobalticebase",
  "cobalticecity",
  "cobalticecomtower",
  "cobalticehq",
  "cobalticelab",
  "cobalticeport",
  "pinkcosmosairport",
  "pinkcosmosbase",
  "pinkcosmoscity",
  "pinkcosmoscomtower",
  "pinkcosmoshq",
  "pinkcosmoslab",
  "pinkcosmosport",
  "tealgalaxyairport",
  "tealgalaxybase",
  "tealgalaxycity",
  "tealgalaxycomtower",
  "tealgalaxyhq",
  "tealgalaxylab",
  "tealgalaxyport",
  "purplelightningairport",
  "purplelightningbase",
  "purplelightningcity",
  "purplelightningcomtower",
  "purplelightninghq",
  "purplelightninglab",
  "purplelightningport",
  "acidrainairport",
  "acidrainbase",
  "acidraincity",
  "acidraincomtower",
  "acidrainhq",
  "acidrainlab",
  "acidrainport",
  "whitenovaairport",
  "whitenovabase",
  "whitenovacity",
  "whitenovacomtower",
  "whitenovahq",
  "whitenovalab",
  "whitenovaport",
  "teleporter",
];

export enum ETerrain {
  NULL,
  PLAIN = 1,
  MOUNTAIN,
  WOOD,
  HRIVER,
  VRIVER,
  CRIVER,
  ESRIVER,
  SWRIVER,
  WNRIVER,
  NERIVER,
  ESWRIVER,
  SWNRIVER,
  WNERIVER,
  NESRIVER,
  HROAD,
  VROAD,
  CROAD,
  ESROAD,
  SWROAD,
  WNROAD,
  NEROAD,
  ESWROAD,
  SWNROAD,
  WNEROAD,
  NESROAD,
  HBRIDGE,
  VBRIDGE,
  SEA,
  HSHOAL,
  HSHOALN,
  VSHOAL,
  VSHOALE,
  REEF,
  NEUTRALCITY,
  NEUTRALBASE,
  NEUTRALAIRPORT,
  NEUTRALPORT,
  ORANGESTARCITY,
  ORANGESTARBASE,
  ORANGESTARAIRPORT,
  ORANGESTARPORT,
  ORANGESTARHQ,
  BLUEMOONCITY,
  BLUEMOONBASE,
  BLUEMOONAIRPORT,
  BLUEMOONPORT,
  BLUEMOONHQ,
  GREENEARTHCITY,
  GREENEARTHBASE,
  GREENEARTHAIRPORT,
  GREENEARTHPORT,
  GREENEARTHHQ,
  YELLOWCOMETCITY,
  YELLOWCOMETBASE,
  YELLOWCOMETAIRPORT,
  YELLOWCOMETPORT,
  YELLOWCOMETHQ,
  REDFIRECITY = 81,
  REDFIREBASE,
  REDFIREAIRPORT,
  REDFIREPORT,
  REDFIREHQ,
  GREYSKYCITY,
  GREYSKYBASE,
  GREYSKYAIRPORT,
  GREYSKYPORT,
  GREYSKYHQ,
  BLACKHOLECITY,
  BLACKHOLEBASE,
  BLACKHOLEAIRPORT,
  BLACKHOLEPORT,
  BLACKHOLEHQ,
  BROWNDESERTCITY,
  BROWNDESERTBASE,
  BROWNDESERTAIRPORT,
  BROWNDESERTPORT,
  BROWNDESERTHQ,
  VPIPE,
  HPIPE,
  NEPIPE,
  ESPIPE,
  SWPIPE,
  WNPIPE,
  NPIPEEND,
  EPIPEEND,
  SPIPEEND,
  WPIPEEND,
  MISSILESILO,
  MISSILESILOEMPTY,
  HPIPESEAM,
  VPIPESEAM,
  HPIPERUBBLE,
  VPIPERUBBLE,
  AMBERBLAZEAIRPORT,
  AMBERBLAZEBASE,
  AMBERBLAZECITY,
  AMBERBLAZEHQ,
  AMBERBLAZEPORT,
  JADESUNAIRPORT,
  JADESUNBASE,
  JADESUNCITY,
  JADESUNHQ,
  JADESUNPORT,
  AMBERBLAZECOMTOWER,
  BLACKHOLECOMTOWER,
  BLUEMOONCOMTOWER,
  BROWNDESERTCOMTOWER,
  GREENEARTHCOMTOWER,
  JADESUNCOMTOWER,
  NEUTRALCOMTOWER,
  ORANGESTARCOMTOWER,
  REDFIRECOMTOWER,
  YELLOWCOMETCOMTOWER,
  GREYSKYCOMTOWER,
  AMBERBLAZELAB,
  BLACKHOLELAB,
  BLUEMOONLAB,
  BROWNDESERTLAB,
  GREENEARTHLAB,
  GREYSKYLAB,
  JADESUNLAB,
  NEUTRALLAB,
  ORANGESTARLAB,
  REDFIRELAB,
  YELLOWCOMETLAB,
  COBALTICEAIRPORT,
  COBALTICEBASE,
  COBALTICECITY,
  COBALTICECOMTOWER,
  COBALTICEHQ,
  COBALTICELAB,
  COBALTICEPORT,
  PINKCOSMOSAIRPORT,
  PINKCOSMOSBASE,
  PINKCOSMOSCITY,
  PINKCOSMOSCOMTOWER,
  PINKCOSMOSHQ,
  PINKCOSMOSLAB,
  PINKCOSMOSPORT,
  TEALGALAXYAIRPORT,
  TEALGALAXYBASE,
  TEALGALAXYCITY,
  TEALGALAXYCOMTOWER,
  TEALGALAXYHQ,
  TEALGALAXYLAB,
  TEALGALAXYPORT,
  PURPLELIGHTNINGAIRPORT,
  PURPLELIGHTNINGBASE,
  PURPLELIGHTNINGCITY,
  PURPLELIGHTNINGCOMTOWER,
  PURPLELIGHTNINGHQ,
  PURPLELIGHTNINGLAB,
  PURPLELIGHTNINGPORT,
  ACIDRAINAIRPORT = 181,
  ACIDRAINBASE,
  ACIDRAINCITY,
  ACIDRAINCOMTOWER,
  ACIDRAINHQ,
  ACIDRAINLAB,
  ACIDRAINPORT,
  WHITENOVAAIRPORT,
  WHITENOVABASE,
  WHITENOVACITY,
  WHITENOVACOMTOWER,
  WHITENOVAHQ,
  WHITENOVALAB,
  WHITENOVAPORT,
  TELEPORTER,
}

export const countryCodes = [
  "os",
  "bm",
  "ge",
  "yc",
  "bh",
  "rf",
  "gs",
  "bd",
  "ab",
  "js",
  "ci",
  "pc",
  "tg",
  "pl",
  "ar",
  "wn",
];

export enum ECountry {
  NEUTRAL,
  ORANGE_STAR,
  BLUE_MOON,
  GREEN_EARTH,
  YELLOW_COMET,
  BLACK_HOLE,
  RED_FIRE,
  GREY_SKY,
  BROWN_DESERT,
  AMBER_BLAZE,
  JADE_SUN,
  COBALT_ICE,
  PINK_COSMOS,
  TEAL_GALAXY,
  PURPLE_LIGHTNING,
  ACID_RAIN,
  WHITE_NOVA,
}

export const unitFilenames = [
  "anti-air",
  "apc",
  "artillery",
  "b-copter",
  "battleship",
  "blackboat",
  "blackbomb",
  "bomber",
  "carrier",
  "cruiser",
  "fighter",
  "infantry",
  "lander",
  "md.tank",
  "mech",
  "megatank",
  "missile",
  "neotank",
  "piperunner",
  "recon",
  "rocket",
  "stealth",
  "sub",
  "t-copter",
  "tank",
];

export const countryUnits = countryCodes
  .map((countryCode) => unitFilenames.map((unit) => `${countryCode}${unit}`))
  .flat();

export function getUnitCode(country: ECountry, unit: EUnit) {
  return unit + (country - 1) * unitFilenames.length;
}

export enum EDecal {
  HP1,
  HP2,
  HP3,
  HP4,
  HP5,
  HP6,
  HP7,
  HP8,
  HP9,
  AMMO,
  FUEL,
  CAPTURE,
  LOAD,
  FOG_LOAD,
  SUB_DIVE,
  SUPPLY_RIGHT,
  TARGET,
  TRAP_RIGHT,
  SELECT,
}

export const decalFilenames = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "aniammo",
  "anifuel",
  "capture",
  "load",
  "fogload",
  "subdive2",
  "supply_right",
  "target_icon2",
  "trap_right",
  "unit_select",
];

export function getDecalMetadata(index: EDecal) {
  const metadata: Partial<ISpriteMetadata> = {
    offsetX: 0,
    offsetY: 0,
  };
  if (index <= EDecal.HP9) {
    metadata.offsetX = 11;
    metadata.offsetY = 11;
  } else if (index === EDecal.AMMO) {
    metadata.offsetX = 12;
    metadata.offsetY = 12;
  } else if (index === EDecal.FUEL) {
    metadata.offsetX = 11;
    metadata.offsetY = 10;
  } else if (index >= EDecal.CAPTURE && index <= EDecal.SUB_DIVE) {
    metadata.offsetX = 2;
    metadata.offsetY = 10;
  } else if (index === EDecal.SUPPLY_RIGHT || index === EDecal.TRAP_RIGHT) {
    metadata.offsetX = 20;
    metadata.offsetY = 5;
  } else if (index === EDecal.SELECT) {
    metadata.offsetX = -1.5;
    metadata.offsetY = -1.5;
  }

  return metadata;
}
